### ISSUE TITLE
[BUG] TinyTag cannot properly read metadata of two folders

### ISSUE THREAD

**Issue by ernieIzde8ski** [devsnd/tinytag#121]
**Describe the bug**
When processing my music library, two albums consistently could not have their genre read properly.

**To Reproduce**
1. `from tinytag import TinyTag; print(TinyTag.get("01. Time What Is Time.mp3").genre)`
2. output is "Other"

**Expected behavior**
Expected output should be "Power Metal."

**Sample File**
https://we.tl/t-qYhsGA9wrq

**Comment by devsnd** [comment]
Sorry @ernieIzde8ski , it took me too long to try to download the file and the link has expired, can you upload it somewhere else, where the files don't expire that quickly please?

**Comment by ernieIzde8ski** [comment]
Sure, [https://drive.google.com/file/d/1RGXO56oXYGeaJgmkYWDaI9OzwHV2-NL4/view?usp=sharing](here's a Google Drive link)

**Comment by devsnd** [comment]
Hey @ernieIzde8ski, 

Thanks for your sample. I was now able to reproduce and to the issue. There are two sources for tag data in that file and one overwrote the other. TinyTag will now preserve the more modern tag data instead of overwriting based on which ever data comes last.

The fix is in the master branch. I'll make a new release in due time, but until then you can just use the master version.
