### ISSUE TITLE
Album and track names longer than 30 characters are truncated

### ISSUE THREAD

**Issue by daboross** [devsnd/tinytag#19]
For instance, `tag.album` gives `'The Double EP: A Sea of Split '` rather than `'The Double EP: A Sea of Split Peas'`. The album name is correctly determined by other programs such as easytag or rythmbox, so I believe it to be correctly encoded in the file.

Edit: seems to occur for track names as well.

**Comment by devsnd** [comment]
Hi Dabo!

sorry for the long wait! Can you upload a track that shows this behavior so I can easily reproduce it? (My bet is on mixed ID3v1/ID3v2 tags...)

Thanks!

**Comment by daboross** [comment]
The album name is truncated on this one: https://copy.com/slrXoFEZaZctArH7

**Comment by devsnd** [comment]
Hey Dabo,

sorry, it took me about three million years to get to this issue and it seems i cannot download the sample from the link anymore or the website is broken... Anyway, would you be so kind and upload it again somewhere?

**Comment by tuankiet65** [comment]
Hmmm, that's weird considering that I can download that sample (I have reuploaded to my Dropbox though https://www.dropbox.com/s/mfsjyjavjnyx3dr/01.01%20-%20Out%20of%20the%20Woodwork.mp3?dl=0)

The bug is still there unfortunately:
```
$ python3
Python 3.5.1 (default, Dec  7 2015, 12:58:09) 
[GCC 5.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from tinytag import TinyTag
>>> TinyTag.get("01.01 - Out of the Woodwork.mp3")
{'track': '1', 'audio_offset': 0, 'duration': 350.4065306122449, 'filesize': 13245163, 'bitrate': 298516.19436782465, 'genre': 'AlternRock', 'artist': 'Courtney Barnett', 'album': 'The Double EP: A Sea of Split ', 'title': 'Out of the Woodwork', 'year': '2013', 'track_total': None, 'samplerate': 44100}
```
![screenshot from 2016-01-26 21-16-31](https://cloud.githubusercontent.com/assets/1905496/12582839/1f0d7d9c-c472-11e5-97c6-680f7ed5bafe.png)

**Comment by devsnd** [comment]
Hey Ho Tuan Kiet, hey Dabo,

Thanks again for helping, I found the bug, It could not correctly read ID3v2.4 tags because it assumed that v2.4 would not use synchsafe bytes (bytes in which the MSB is always set to 0).

Well, who cares about the technical details? It should work now. And as a special bonus I also fixed how the genre is read. Look at the screenshot above. See the genre? Its `40`. But It should be Alternative Rock, seems to be a glitch in Amazon MP3s. Well TinyTag fixes those:

    >>> from tinytag import TinyTag
    >>> TinyTag.get('/home/tom/data/projects/tinytag/01.01 - Out of the Woodwork.mp3')
{'samplerate': 44100, 'album': 'The Double EP: A Sea of Split Peas', 'duration': 350.4065306122449, 'channels': 2, 'disc_total': '1', 'audio_offset': 170234, 'bitrate': 298516.19436782465, 'genre': 'AlternRock', 'track': '1', 'title': 'Out of the Woodwork', 'year': '2013', 'track_total': '12', 'filesize': 13245163, 'artist': 'Courtney Barnett', 'disc': '1'}
