### ISSUE TITLE
self.samplerate is None when reading Ogg with Opus codec

### ISSUE THREAD

**Issue by tuankiet65** [devsnd/tinytag#31]
Python output:
```
>>> from tinytag import TinyTag
>>> TinyTag.get("a.ogg")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.5/site-packages/tinytag/tinytag.py", line 94, in get
    tag.load(tags=tags, duration=duration, image=image)
  File "/usr/lib/python3.5/site-packages/tinytag/tinytag.py", line 115, in load
    self._determine_duration(self._filehandler)
  File "/usr/lib/python3.5/site-packages/tinytag/tinytag.py", line 480, in _determine_duration
    self.duration = self._max_samplenum / float(self.samplerate)
TypeError: float() argument must be a string or a number, not 'NoneType'
```

FFprobe output:
```
Input #0, ogg, from 'a.ogg':
  Duration: 00:05:19.43, start: 0.000000, bitrate: 177 kb/s
    Stream #0:0: Audio: opus, 48000 Hz, stereo, fltp
    Metadata: [...]
```

The file in question: [music.zip](https://github.com/devsnd/tinytag/files/202899/music.zip)

**Comment by devsnd** [comment]
Hey Ho Tuan Kiet,

Thanks a lot for your bug report! Instead of just catching the error I instead implemented ful blown Opus support. Thanks also for the music sample, that helped a lot! The fix is already merged into the master, but I still need to release a new version in a few minutes once the [tests on travis](https://travis-ci.org/devsnd/tinytag) run through.

Have a nice day and have some icecream :ice_cream:

**Comment by tuankiet65** [comment]
Thanks for that! I though this ticket would go unnoticed but it didn't :+1:
