### ISSUE TITLE
Comment Fields

### ISSUE THREAD

**Issue by CodeMouse92** [devsnd/tinytag#42]
Would it be possible for tinytag to expose the ID3 "comment" field?

**Comment by devsnd** [comment]
Hey Jason, sorry for the long wait, I must have missed the notification!

The `comment` field is actually already parsed but not yet exposed. I think it's used for saving the track number in some of the weirder ID3 specs. So technically it should be very simple to make it part of the TinyTag.

Do you want to try to make a PR ready yourself?

**Comment by CodeMouse92** [comment]
I would, but honestly, the entire ID3 system makes my head swim.

**Comment by devsnd** [comment]
Hey bmiller,

it looks like this might be all needed to make this work. Can you make a
pull request? I'll implement the comment field for the remaining formats
then eventually

**Comment by devsnd** [comment]
Hey @bmiller1961,

I am stuck at the airport so I took the time to implement this using your code. The changes are available in the master branch, I will release a version once all the tests run through!

**Comment by bmiller1961** [comment]
Hey @ devsnd,
I was out of town for the past few days and just got the messages today. I didn't mean for you to go through the trouble of adding this function but hopefully other people need this.
Anyway I downloaded the new code and it works the same as before with the comment field added. This version and the older version always show the mp3 genre as "other" but I think that is because Windows places this information in a secondary location. It's not a big deal but you might want to document it as a known issue.
Let me know if you need me to do anything for you. I will try to make a "pull request" but I've never used this site before so forgive me if I do it incorrectly.

**Comment by bmiller1961** [comment]
oops. I guess it's a little late to add a pull request. Anyway let me know if that would help and I will be glad to upload the code that I have.

**Comment by devsnd** [comment]
Hey guys, this seems to be implemented already, like a long time ago. I'm closing this ticket, have a nice day!
