### ISSUE TITLE
Issue with album art data

### ISSUE THREAD

**Issue by candh** [devsnd/tinytag#45]
I need to get cover art and other data for some of my music files. Seems like most of the tag parsing libraries only give me the cover art of MP3, but that's fine..

Anyways, I couldn't get my image to display because some of the bytes data is truncated, according to Pillow, at least. I even loaded the bytes with the PyQt library to display on the GUI, but it can't load from the data.

Then I loaded [mutagen](https://mutagen.readthedocs.io/en/latest/), which is a little more non-intuitive to use than tinytag. But anyways, I got bytes data from both the libraries and compared them on [diffnow](https://www.diffnow.com/)

I tried it with 2 files, and apparently tinytag does cut out some data from the beginning. I could get the bytes data from mutagen to display perfectly. 

I have uploaded the reports from both analysis here: https://drive.google.com/open?id=1EZ7XMPoQsrEaeQmZZ3Z-nwK2XM66EVBZ
Please take a look... Here are some screenshots from the analysis

Here's the difference of the first analysis. The first line is TinyTag and the second line is Mutagen
<img width="730" alt="screen shot 2018-02-10 at 10 46 06 pm" src="https://user-images.githubusercontent.com/11281452/36064911-46fd4d08-0eb4-11e8-832f-805cb8551ec6.png">

Here's the second one. Same thing

<img width="712" alt="screen shot 2018-02-10 at 10 46 22 pm" src="https://user-images.githubusercontent.com/11281452/36064925-7a0f944e-0eb4-11e8-9328-4049859d87f3.png">
 
Is this a bug? I hope this is fixed in a future version. 
Thank you so much for the amazing library.

**Comment by devsnd** [comment]
Hey @candh, thanks for your excellent bug report!

I'd love to solve this, but I still need you to upload the mp3, so I can take a closer look at the data.

**Comment by candh** [comment]
Thanks @devsnd for the quick reply.

I have uploaded both the mp3s here https://drive.google.com/drive/folders/1WM_wQRmZyp3zCWF2UfI1qnSWwUunHNhf

**Comment by devsnd** [comment]
Hey @candh,

Thanks for providing the samples. Using the samples and your investigation with the binary diffs I knew that there must be a bug in the parser for the image container, because the image header was missing some bytes in the beginning.

Interestingly the parser problem was masked by another bug (that's why it worked most of the time). So we hit two birds with one stone here! 🐦 🐦 🔫 😸 

Your issue should now be resolved in `master`. I will release a new version promptly. If you find any more problems feel free to open another issue.

Thanks again for your help improving tinytag!
Have a piece of cake 🍰

**Comment by candh** [comment]
Sure, no problem! I'll check it out..
Thanks for the great work. 🙂

**Comment by swagardson** [comment]
I feel like an idiot, because I pip installed tinytag and just hit this same issue and was trying to resolve it (my temp solution was to set `self._image_data = content[desc_start_pos:]`), and then I realized the row counts between the main scripts were off when I looked at the repository... 

I see now that 0.19.0 is the current version while PyPI still has version 0.18.0. You live and you learn, I guess! :sweat_smile:
