### ISSUE TITLE
Invalid duration

### ISSUE THREAD

**Issue by diatomee** [devsnd/tinytag#69]
Hello. I open this ticket which seems to correspond to #37.
I have an album with tracks about twice as long as their true duration. I send a mp3 file by email.

**Comment by vandys** [comment]
I'm seeing what looks like 2X with an mp3 on this code path:

  if frames == 0 and ID3._USE_XING_HEADER:

mp3 generated by lame, for a 48k ABR mp3.  When I encode at 96k ABR, it's not off by
a factor of 2.  So it appears to be bit rate, not channels, which throws off the interpretation
of the xing header.  My wife's a musician, I can encode one of her tracks (no license issues)
if you need some example mp3's.

**Comment by vandys** [comment]
In any case, in _parse_xing_header() the TOC values are bytes, not 4-byte big endian values.
But that doesn't change the duration calculation...

**Comment by devsnd** [comment]
Wowzeee, It now takes me a year to answer github issues :cry: 

Anyway, if you still have any of the files at hand, please post them, so this issue can be reproduced!

**Comment by vandys** [comment]
Sure... compare soxi on https://vsta.org/andy/pickup/qz9k29290006-48.mp3 versus what tinytag says for duation.  (It's my wife's track, so copyright/music licensing is no problem, enjoy!)

BTW, welcome back.

**Comment by devsnd** [comment]
Hey @vandys , thanks for the sample file. That and your comment about an off by a factor of 2 lead me to some investigation about the mp3 format. It turns out that the mp3 frames have 1152 samples *per channel*. My test for the xing header was using a mono-channel file, so your stereo file was off by a factor of 2 :facepalm: 

Anyway I have fixed the issue an your file is now correctly read. I am using a truncated version of your file for the test-suite now.

Thanks for your hints and your patience! You can use the version here in git until the next version is released containing this fix.

Have a great day in these weird times, maybe you'd fancy some cake? here you go: :moon_cake:

**Comment by vandys** [comment]
Thanks much!
