### ISSUE TITLE
Output garbled characters when ID3V1 contains Chinese characters.

### ISSUE THREAD

**Issue by cdhigh** [devsnd/tinytag#75]
I changed this line to `return self._unpad(codecs.decode(x, 'gbk'))` got the correct meta data.
https://github.com/devsnd/tinytag/blob/e9b301d9a9bc2e7645c3b6364a593ce09c32736a/tinytag/tinytag.py#L607

Add an option of encoding? or other solution?

**Comment by cdhigh** [comment]
Added: ID3V2 has same bug.

**Comment by cdhigh** [comment]
I try with locale module, it works.
locale.getpreferredencoding(False)
or 
decode using `locale.getpreferredencoding(False)`, if failed, try 'latin1'?

**Comment by devsnd** [comment]
Hey cdhigh,

I have another idea to make this possible that is similar to your PR, which is to use `chardet` instead of the system locale. Maybe you can make a test using that library and we could add it as optional dependency to tinytag.

Chardet uses the "letter-frequency" of the bytes to determine which encoding might be successfully used.

https://pypi.org/project/chardet/

**Comment by cdhigh** [comment]
chardet return latin1 when title contains chars Chineses.

**Comment by devsnd** [comment]
Hey @cdhigh ,

Could you please provide a sample file so I can reproduce the bug?

**Comment by cdhigh** [comment]
https://we.tl/t-cs2f6K6j66

**Comment by devsnd** [comment]
Hey @cdhigh 

Thanks for providing a sample file, I was able to reproduce the bug. Unfortunately, there is no way to automatically detect the correct encoding for gbk encoded files. (As you also saw, chardet misdetects it as another encoding).

I don't want to fill the library with code that guesses encodings based on system settings and whatnot, so instead I opted to allow for overriding the default encoding.

You can now use `TinyTag.get(filename, encoding='gbk')` and it will then use `gbk` encoding whenever no encoding has been specified inside of the mp3 file. Since gbk also contains the ASCII character set, this should work pretty well for you, even when you also have english files in between.
